spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: [your db url]
    username: [your db username]
    password: [your db password]
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: [your db timezone]
        show_sql: true
        highlight_sql : true
  data:
    redis:
      host: [your redis url]
      port: [your redis port]
  oauth2:
    client:
      provider:
        kakao:
          authorization-uri: https://kapi.kakao.com/v2/user/me
          unlink-uri: https://kapi.kakao.com/v1/user/unlink

  # 메일용 thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

server:
  error:
    include-message: never

jwt:
  header: Authorization
  secret: [your jwt secret]
  access-token-validity-in-seconds: 1000
  refresh-token-validity-in-seconds : 2000

smtp:
  host: [your smtp host]
  username: [your smtp username]
  password: [your smtp password]
  port: [your smtp port]

verification:
  server-uri: [your server url]
  email:
    expire-time: 3600
    do-email-verification: true


logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%mdc{traceId}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
